# Generated by Django 4.1.9 on 2023-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_tentronmessagetask_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
