# Generated by Django 4.1.9 on 2023-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_messagerecipient_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontent',
            name='title',
            field=models.CharField(default='default title', max_length=255),
            preserve_default=False,
        ),
    ]
