# Generated by Django 4.1.8 on 2023-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_members_organizationmembership'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', through='organization.OrganizationMembership', to='organization.organization'),
        ),
    ]
