# Generated by Django 4.1.9 on 2023-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_organizationrootpage_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='The custom CSS of the site. without <style> tag.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_js',
            field=models.TextField(blank=True, help_text='The custom JavaScript of the site. without <script> tag.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow: /', help_text='The robots.txt of the site. Default is disallow all.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sitemap_active',
            field=models.BooleanField(default=False, help_text='Check to enable sitemap'),
        ),
    ]
