# Generated by Django 4.1.9 on 2023-05-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_sitesettings_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, help_text='The fixed contact address of the site.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='The fixed contact email of the site.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='The fixed contact phone of the site.', max_length=255, null=True),
        ),
    ]
