# Generated by Django 4.1.9 on 2023-06-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_sitesettings_site_favorite_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrootpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
    ]
