# Generated by Django 4.1.9 on 2023-06-15 08:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('organization', '0009_organizationrootpage_disable_breadcrumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_menu', wagtail.fields.StreamField([('column', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='organization_menu.organizationflatmenu'))], blank=True, help_text='The footer menu of the site.', null=True, use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Menu',
                'verbose_name_plural': 'Footer Menu',
            },
        ),
    ]
