# Generated by Django 4.1.10 on 2023-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
        ('organization', '0011_alter_footermenu_footer_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='template_folder',
        ),
        migrations.AddField(
            model_name='organization',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text="Enable SSL, becareful the limit of Let's Encrypt."),
        ),
        migrations.CreateModel(
            name='SiteSettingsTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('site_settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings_theme', to='organization.sitesettings')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_site_settings', to='theme.theme')),
            ],
            options={
                'verbose_name': 'Site Settings Theme',
                'verbose_name_plural': 'Site Settings Themes',
            },
        ),
    ]
