# Generated by Django 4.1.10 on 2023-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_remove_sitesettings_template_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
