# Generated by Django 4.1.9 on 2023-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_faqitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='category_tab_mode',
            field=models.BooleanField(default=True, help_text='Check to show categories as tabs'),
        ),
    ]
