# Generated by Django 4.1.9 on 2023-06-09 07:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faqpage_category_tab_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='sub_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
