# Generated by Django 4.1.9 on 2023-06-10 07:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_body_teamdetailpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetailpage',
            name='social',
            field=wagtail.fields.StreamField([('socials', wagtail.blocks.StructBlock([('social_name', wagtail.blocks.CharBlock(required=False)), ('social_link', wagtail.blocks.CharBlock(required=True)), ('icon', wagtail.blocks.CharBlock(default='fab fa-facebook-f', help_text='Font Awesome Icon', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
