# Generated by Django 4.1.9 on 2023-06-12 01:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='body',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('testimonials', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('subheading', wagtail.blocks.CharBlock(required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtailmodelchooser.blocks.ModelChooserBlock(target_model='core.testimonialitem')))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('testimonials', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('subheading', wagtail.blocks.CharBlock(required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtailmodelchooser.blocks.ModelChooserBlock(target_model='core.testimonialitem')))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
