# Generated by Django 4.1.9 on 2023-06-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0009_blogcategory_blogtag_alter_blogdetailpage_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtag',
            unique_together={('name', 'slug', 'site')},
        ),
    ]
