# Generated by Django 4.1.9 on 2023-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blogdetailpage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('audio', 'Audio'), ('video', 'Video'), ('gallery', 'Gallery')], default='standard', max_length=50),
        ),
    ]
