# Generated by Django 4.1.9 on 2023-06-15 03:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_servicedetailpage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListPageServiceDetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail_pages', to='core.servicelistpage')),
                ('service_detail_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_list_pages', to='core.servicedetailpage')),
            ],
            options={
                'unique_together': {('page', 'service_detail_page')},
            },
        ),
    ]
