# Generated by Django 4.1.9 on 2023-06-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servicelistpageservicedetailpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicelistpageservicedetailpage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='servicelistpageservicedetailpage',
            unique_together=set(),
        ),
    ]
