# Generated by Django 4.1.9 on 2023-06-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_servicelistpageservicedetailpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='bloglistpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='productform',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='productlistpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='projectdetailpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='servicedetailpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='servicelistpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='teamdetailpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='teamlistpage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AddField(
            model_name='thankyoupage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
    ]
