# Generated by Django 4.1.9 on 2023-06-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutpage_disable_breadcrumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelistpage',
            name='heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicelistpage',
            name='subheading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
