# Generated by Django 4.1.9 on 2023-06-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_servicelistpage_heading_servicelistpage_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
    ]
