# Generated by Django 4.1.9 on 2023-06-17 03:33

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_thankyoupage_body_thankyoupage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(required=True)), ('author', wagtail.blocks.CharBlock(required=False)), ('author_title', wagtail.blocks.CharBlock(required=False)), ('quotation_link', wagtail.blocks.CharBlock(required=False)), ('footer_text', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False))])), ('image_content_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(required=False))])), ('testimonials', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('subheading', wagtail.blocks.CharBlock(required=False)), ('testimonials', wagtail.blocks.ListBlock(wagtailmodelchooser.blocks.ModelChooserBlock(target_model='core.testimonialitem')))])), ('video', wagtail.embeds.blocks.EmbedBlock(max_height=400, max_width=800)), ('audio', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True))])), ('carousel', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=True)))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
