# Generated by Django 4.1.10 on 2023-07-22 13:07

import core.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_aboutpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', core.blocks.TentronTableBlock(table_options={'autoColumnSize': True, 'colHeaders': False, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'editor': 'text', 'height': 216, 'minSpareRows': 0, 'renderer': 'html', 'rowHeaders': False, 'startCols': 4, 'startRows': 6, 'stretchH': 'all'})), ('typed_table', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('text', wagtail.blocks.CharBlock()), ('numeric', wagtail.blocks.FloatBlock()), ('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
