# Generated by Django 4.1.8 on 2023-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapejs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grapejspage',
            old_name='content',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='grapejspage',
            name='json_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
