# Generated by Django 4.1.8 on 2023-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapejs', '0002_rename_content_grapejspage_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapejspage',
            name='css_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grapejspage',
            name='json_content',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
