# Generated by Django 4.1.8 on 2023-05-11 05:41

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grapejs', '0003_grapejspage_css_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapejspage',
            name='content',
            field=wagtail.fields.StreamField([('grapejs', wagtail.blocks.StructBlock([('json_content', wagtail.blocks.TextBlock(help_text='GrapeJs json content', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='grapejspage',
            name='json_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
