# Generated by Django 4.1.8 on 2023-05-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('grapejs', '0007_custompage_repeat_in_subnav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='breadcrumb_background',
            field=models.ForeignKey(blank=True, help_text='The background image for the breadcrumb section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
