# Generated by Django 4.1.9 on 2023-06-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapejs', '0008_custompage_breadcrumb_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
    ]
