# Generated by Django 4.1.9 on 2023-06-15 05:11

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='disable_breadcrumb',
            field=models.BooleanField(default=False, help_text='Disable the breadcrumb section for this page.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('default_slider', wagtail.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(required=True)), ('heading', wagtail.blocks.CharBlock(required=False)), ('subheading', wagtail.blocks.CharBlock(required=False)), ('context', wagtail.blocks.RichTextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False))])), ('swiper_slider', wagtail.blocks.StructBlock([('sliders', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('background', wagtail.images.blocks.ImageChooserBlock(required=True)), ('heading', wagtail.blocks.CharBlock(required=False)), ('subheading', wagtail.blocks.CharBlock(required=False)), ('context', wagtail.blocks.RichTextBlock(required=False)), ('button_text', wagtail.blocks.CharBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
