# Generated by Django 4.1.8 on 2023-04-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmainmenu',
            options={'verbose_name': 'Organization Main Menu', 'verbose_name_plural': 'Organization Main Menus'},
        ),
    ]
