# Generated by Django 4.1.9 on 2023-06-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_menu', '0003_organizationflatmenu_organizationflatmenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationflatmenu',
            options={'verbose_name': 'Flat Menu', 'verbose_name_plural': 'Flat Menus'},
        ),
    ]
